# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simpel Moving Average with a Matrix as input
#'
#' @param X a matrix of which one want to calculate simpel moving average
#' @param period number one want to use when taking simpel moving average
#'
#' @export
SMAMatrixCpp <- function(X, period) {
    .Call('_IPAMomentum_SMAMatrixCpp', PACKAGE = 'IPAMomentum', X, period)
}

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call('_IPAMomentum_timesTwo', PACKAGE = 'IPAMomentum', x)
}

