# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title getTransPrice
#' @description
#' Returns trades
#' @name getTransPrice
#' @param X matrix with weights
#'
#' @export
NULL

getTransPrice <- function(X, Y) {
    .Call('_IPAMomentum_getTransPrice', PACKAGE = 'IPAMomentum', X, Y)
}

#' @title numberTradesMatrixCpp
#' @description
#' Returns trades
#' @name numberTradesMatrixCpp
#' @param X matrix with weights
#'
#' @export
NULL

numberTradesMatrixCpp <- function(X) {
    .Call('_IPAMomentum_numberTradesMatrixCpp', PACKAGE = 'IPAMomentum', X)
}

#' @title sdRollingMatrixCpp
#' @description
#' SD rolling over specified period with matrix as output
#' @name sdRollingMatrixCpp
#' @param X a matrix of which one want to calculate SD rolling
#' @param period number one want to use when taking SD rolling
#'
#' @export
sdRollingMatrixCpp <- function(X, period) {
    .Call('_IPAMomentum_sdRollingMatrixCpp', PACKAGE = 'IPAMomentum', X, period)
}

#' @title sdRollMatrixCpp
#' @description
#' SD rolling over specified period with matrix as output
#' @name sdRollMatrixCpp
#' @param X a matrix of which one want to calculate SD rolling
#' @param period number one want to use when taking SD rolling
#'
#' @export
sdRollMatrixCpp <- function(X, period) {
    .Call('_IPAMomentum_sdRollMatrixCpp', PACKAGE = 'IPAMomentum', X, period)
}

#' @title Simpel Moving Average with a Matrix as input
#' @description
#' Returns simplle moving average
#' @name SMAMatrixCpp
#' @param X a matrix of which one want to calculate simpel moving average
#' @param period number one want to use when taking simpel moving average
#'
#' @export
SMAMatrixCpp <- function(X, period) {
    .Call('_IPAMomentum_SMAMatrixCpp', PACKAGE = 'IPAMomentum', X, period)
}

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call('_IPAMomentum_timesTwo', PACKAGE = 'IPAMomentum', x)
}

#' @title weightsPropMatrix
#' @description
#' Returns weights given t-statistics and a confidence level
#' @name weightsPropMatrix
#' @param x A numeric matrix of t-statistics
#' @param cf double confidence level
#' @param k int lockback period
#'
#' @export
NULL

weightsPropMatrix <- function(X, cf, k) {
    .Call('_IPAMomentum_weightsPropMatrix', PACKAGE = 'IPAMomentum', X, cf, k)
}

